enum Level{
  LEVEL_BEGIN,
  LEVEL_SET,
  LEVEL_MAP1,
  LEVEL_LOGIN,
  LEVEL_LANBATTLE,
  LEVEL_END,
  LEVEL_RANK,
  LEVEL_START,
  LEVEL_STORY,
  LEVEL_TOTURIAL,
  LEVEL_MAP2,
  LEVEL_ROGUE,
  LEVEL_END2,
  LEVEL_MODECHOOSE
}
